name: build-windows-latest

on:
  push:
    branches:
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:
    name: Build node on windows-latest
    runs-on: windows-latest
    steps:
      - name: Release version number
        run: echo '::set-output name=RELEASE_VERSION::v0.1.0'
        id: release-version-number
      - name: Get release version
        run: echo "The version number is ${{ steps.release-version-number.outputs.RELEASE_VERSION }}"
      - uses: actions/checkout@v3
      - name: Cache sccache results
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cargo/cache
          key: ${{ runner.os }}-0001
      - name: Build windows-latest
        run: |
          rustup check
          case "$OSTYPE" in
            msys)
              echo "Windows doesn't like it when rustup updates itself"
              rustup update --no-self-update stable
              ;;
            *)
              echo "Linux and macOS don't need manual suppression of rustup self update"
              rustup update stable
              ;;
          esac
          rustup check
          rustup component add rustfmt
          rustup component add clippy
          ./ci/all.sh
          ./ci/multinode_integration_test.sh
          ./ci/collect_results.sh
        shell: bash
      - name: Publish windows-latest
        uses: actions/upload-artifact@v3
        with:
          name: Build Results windows-latest-${{ steps.release-version-number.outputs.RELEASE_VERSION }}
          path: results
          
