name: ci-matrix

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Cache sccache results
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cargo/cache
          key: ${{ runner.os }}-0001
      - name: Build ${{ matrix.os }}
        run: |
          rustup check
          rustup self update
          bash -cxev "rustup update stable"
          rustup check
          rustup component add rustfmt
          rustup component add clippy
          ./ci/all.sh
          ./ci/multinode_integration_test.sh
          ./ci/collect_results.sh
        shell: bash
      - name: Publish ${{ matrix.os }}
        uses: actions/upload-artifact@v1
        with:
          name: Build Results ${{ matrix.os }}
          path: results
