name: ci-matrix

on:
  push:
    branches:
      # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
      - 'release/**'
      - 'hotfix/**'

jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Cache sccache results
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.cargo/cache
          key: ${{ runner.os }}-0001
      - name: Build ${{ matrix.os }}
        run: |
          rustup check
          case "$OSTYPE" in
            msys)
              echo "Windows doesn't like it when rustup updates itself"
              rustup update --no-self-update stable
              ;;
            *)
              echo "Linux and macOS don't need manual suppression of rustup self update"
              rustup update stable
              ;;
          esac
          rustup check
          rustup component add rustfmt
          rustup component add clippy
          ./ci/all.sh
          ./ci/multinode_integration_test.sh
          ./ci/collect_results.sh
        shell: bash
        
      - run:   |
         upload_url=$(curl -sL https://api.github.com/repos/actions/checkout/releases/latest | jq -r '.upload_url')
         echo UPLOAD_URL=$upload_url >> $GITHUB_ENV
         shell: bash

      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
      - name: Publish ${{ matrix.os }}
        uses: actions/upload-artifact@v3
        with:
          name: Build Results ${{ matrix.os }}
          path: results/generated/bin
