name: ci-matrix

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  build:

    name: Build node on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache sccache results
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
         path: |
            ~/.cargo/cache/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
         key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build ubuntu-latest
        run: |
          rustup check
          case "$OSTYPE" in
            msys)
              echo "Windows doesn't like it when rustup updates itself"
              rustup update --no-self-update stable
              ;;
            *)
              echo "Linux and macOS don't need manual suppression of rustup self update"
              rustup update stable
              ;;
          esac
          rustup check
          rustup component add rustfmt
          rustup component add clippy
        shell: bash
      - name: Publish ubuntu-latest
        uses: actions/upload-artifact@v3
        with:
          name: Node-linux
          path: masq
