name: ci-matrix

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  build:
    name: Build node
    runs-on: [ubuntu-22.04, windows-2022, macos-12]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: testing ls
        run: |
          ls
          cd node/ci
          ls
          cd ../automap
          ls
      
