name: s3-release

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
   build:
       runs-on: ubuntu-latest
       steps:
        - name: 'Echo download path'
          run: |
            echo ${{ github.ref_name }}
