name: latest-release

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master

jobs:
   build:
       runs-on: ubuntu-latest
       steps:
        - name: 'Echo download path'
          run: |
            echo ${{ github.head_ref }}
            echo ${{ github.event.pull_request.head.sha }}
