name: latest-release

on:
  push:
    branches:
      - master

jobs:
   build:
       runs-on: ubuntu-latest
       steps:
        - name: 'Echo originating branch'
          run: |
            echo ${{ github.head_ref }}
            echo ${{ github.event.pull_request.head.sha }}
            echo ${{ github.event.pull_request.number }}
            echo ${{ github.event.workflow_run.id }}
