name: s3-release

on:
  workflow_run:
    workflows: [ci-matrix]
    types: [completed]

jobs:
  successful_test:
       if: startsWith(github.head_ref, 'v*') != true and startsWith(github.event.workflow_run.conclusion, 'success') == true
       runs-on: ubuntu-latest
       env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       steps:
        - uses: actions/checkout@v3
        - name: Echo results
          run: |
            echo "the test was a success"
  unsuccessful_test:
       if: startsWith(github.head_ref, 'v*') != true and startsWith(github.event.workflow_run.conclusion, 'success') != true
       runs-on: ubuntu-latest
       env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       steps:
        - uses: actions/checkout@v3
        - name: Echo results
          run: |
            echo "the test was NOT a success"
