name: s3-release

on:
  push:
    tags:
      - v*

jobs:
   run_if:
       if:  startsWith(github.head_ref, 'v*')
       runs-on: ubuntu-latest
       steps:
        - name: 'Echo download path'
          run: echo ${{github.head_ref}}
