name: s3-release

on:
  workflow_run:
    workflows: [latest-release]
    types:
      - completed

jobs:
   echo:
       runs-on: ubuntu-22.04
       steps:
        - name: 'Echo github events'
          run: |
            echo ${{ github.ref_name }}
            echo ${{ github.head_ref_name }}
            echo ${{ github.event.workflow_run.head_branch }}
            echo ${{ github.event.workflow_run.head_sha }}
            echo ${{ github.event.workflow_run.id }}
