name: s3-release

on:
  pull_request:
    types:
      - closed

jobs:
   build:
       if: github.event.pull_request.merged == true
       runs-on: ubuntu-22.04
       steps:
        - name: 'Echo download path'
          run: |
            echo ${{ github.ref_name }}
            echo ${{ github.event.pull_request }}
