name: s3-release

on:
  pull_request:
    types:
      - closed

jobs:
   build:
       if: github.event.pull_request.merged == true
       runs-on: ubuntu-22.04
       steps:
        - name: 'Echo github events'
          run: |
            echo ${{ github.ref_name }}
            echo ${{ github.event.pull_request.number }}
            echo ${{ github.event.pull_request.pull_request }}
            echo ${{ github.event.workflow_run.id }}
